### ISSUE TITLE
where is api connect dashboard or sandbox link/button?

### ISSUE THREAD

**Issue by ghost** [IBM/api-connect-oauth-tutorial#1]
I am not able to follow your tutorial instructions at - 
https://developer.ibm.com/tutorials/securing-apis-oauth2-api-connect/

Step 3 Configure API Connect
Note the endpoint url in API Connect:
On the API Connect Dashboard, click Sandbox.

where is api connect dashboard or sandbox link/button?

**Comment by balajikadambi** [comment]
@kalllol Once you create an API Connect instance on IBM Cloud, you can launch the API Connect Dashboard. After that you can follow the instructions as seen in the gif image.

**Comment by ghost** [comment]
Thanks @balajikadambi 
I have already created API Connect instance on step 1 (Create an instance of IBM API Connect. Ensure that the Lite plan is selected, and then click Create)

However, I see a **blank screen** in Chrome browser when trying to get to newly created instance.
Then i navigate to https://cloud.ibm.com/apis/overview
and see attched screenshot
![api connect screen](https://user-images.githubusercontent.com/20995313/73666671-c55d7180-4668-11ea-86ba-066b441d1968.png)

here are a couple of browser errors -

authorize?client_id=apiconnect&response_type=code&scope=openid+cloud_controller.write+cloud_controller.read&redirect_uri=https%3A//login.service.us.apiconnect.ibmcloud.com/auth/callback&state={"redirectURL"%3A"https%3A//apimanager.us-south.apiconnect.cloud.ibm.com/apim/openid/j_security_check?region%3Dus-south%26guid%3D2bac6af9-f8d4-4ad6-995e-0da9bbbcd172%26env_id%3Dibm%3Ayp%3Aus-south%26authUrl%3Dhttps%3A//mccp.us-south.cf.cloud.ibm.com/login%26spaceId%3Db2414bb8-2a71-4900-bb45-13d6b43cc931%26org%3D5e383c910cf2f67403230a81%26apim_url%3Dhttps%3A//apimanager.us-south.apiconnect.cloud.ibm.com/apim/?org%3D5e383c910cf2f67403230a81%26region%3Dus-south%26spaceId%3Db2414bb8-2a71-4900-bb45-13d6b43cc931%26authUrl%3Dhttps%3A%2F%2Fmccp.us-south.cf.cloud.ibm.com%2Flogin"}:1 GET https://apimanager.us-south.apiconnect.cloud.ibm.com/apim/openid/j_security_check?region=us-south&region=us-south&guid=2bac6af9-f8d4-4ad6-995e-0da9bbbcd172&env_id=ibm%3Ayp%3Aus-south&authUrl=https%3A%2F%2Fmccp.us-south.cf.cloud.ibm.com%2Flogin&authUrl=https%3A%2F%2Fmccp.us-south.cf.cloud.ibm.com%2Flogin&spaceId=b2414bb8-2a71-4900-bb45-13d6b43cc931&spaceId=b2414bb8-2a71-4900-bb45-13d6b43cc931&org=5e383c910cf2f67403230a81&apim_url=https%3A%2F%2Fapimanager.us-south.apiconnect.cloud.ibm.com%2Fapim%2F%3Forg%3D5e383c910cf2f67403230a81&code=dd3n420l3bo7 400
(anonymous) @ authorize?client_id=apiconnect&response_type=code&scope=openid+cloud_controller.write+cloud_controller.read&redirect_uri=https%3A//login.service.us.apiconnect.ibmcloud.com/auth/callback&state={"redirectURL"%3A"https%3A//apimanager.us-south.apiconnect.cloud.ibm.com/apim/openid/j_security_check?region%3Dus-south%26guid%3D2bac6af9-f8d4-4ad6-995e-0da9bbbcd172%26env_id%3Dibm%3Ayp%3Aus-south%26authUrl%3Dhttps%3A//mccp.us-south.cf.cloud.ibm.com/login%26spaceId%3Db2414bb8-2a71-4900-bb45-13d6b43cc931%26org%3D5e383c910cf2f67403230a81%26apim_url%3Dhttps%3A//apimanager.us-south.apiconnect.cloud.ibm.com/apim/?org%3D5e383c910cf2f67403230a81%26region%3Dus-south%26spaceId%3Db2414bb8-2a71-4900-bb45-13d6b43cc931%26authUrl%3Dhttps%3A%2F%2Fmccp.us-south.cf.cloud.ibm.com%2Flogin"}:1
apiconnect?apim_url=https%3A%2F%2Fapimanager.us-south.apiconnect.cloud.ibm.com%2Fapim%2F%3Forg%3D5e383c910cf2f67403230a81%26region%3Dus-south%26spaceId%3Db2414bb8-2a71-4900-bb45-13d6b43cc931%26authUrl%3Dhttps%3A%2F%2Fmccp.us-south.cf.cloud.ibm.com%2Flogin&guid=2bac6af9-f8d4-4ad6-995e-0da9bbbcd172:5 GET https://js-agent.newrelic.com/nr-1158.min.js net::ERR_ABORTED 403 (Forbidden)

**Comment by balajikadambi** [comment]
It appears to be a browser cache issue. Login to IBM Cloud in a private window and access the API Connect instance. If it works, then clear the browser cache and restart the browser. Then access the API Connect instance. You should see the below screen:
<img width="905" alt="Screenshot 2020-02-04 at 09 05 30" src="https://user-images.githubusercontent.com/25296042/73711742-d45a2780-472d-11ea-9811-cb83006fd93d.png">

**Comment by ghost** [comment]
I realize the IBM website code defect at https://cloud.ibm.com is unrelated to your tutorial but I sincerely appreciate your help. Thank you so much!

I will close the issue as the work around is to create an API using the newly created API service and then wait for all background activities to finally present the dynamically generated dashboard page as response

the user behavior related feedback items are -
1. the cloud.ibm.com web site does not handle error when the api service does not have any api 
2. there is no menu navigation available to the api conncet dashboard and the steps to get to api connect dashboard is vague and ambiguous
3. ibm cloud dashboard and api connect dashboard are 2 different user experiences related by random events
